---
page_title: Help for households
metadata:
  title: Cost of living support
  description: >-
    Find out what support is available to help with the cost of living. This
    includes income and disability benefits, bills and allowances, childcare,
    housing and transport.
