---
page_title: Cost of living support
metadata:
  title: Cost of living support
  description: >-
    Find out what support is available to help with the cost of living. This
    includes income and disability benefits, bills and allowances, childcare,
    housing and travel.
announcements:
  heading: Announcements
  body:
  - content: There will be an automatic limit on how much you will be charged for each unit of gas or electricity from 1 October.
    link_text: Find out how the Energy Price Guarantee limits your energy prices.
    href: /government/publications/energy-bills-support/energy-bills-support-factsheet-8-september-2022
  - content: You may get calls, emails or messages that pretend to be from a government service or energy bill support scheme. If you get a message asking for your personal details (for example, bank details or passwords) this could be a scam.
    link_text: Report anything you think is suspicious.
    href: /report-suspicious-emails-websites-phishing
header:
  heading: Cost of living support
  lede: Find out what support is available to help with the cost of living. This includes income and disability benefits, bills and allowances, childcare, housing and travel.
  link_text: Check what benefits and financial support you can get
  href: /check-benefits-financial-support
body:
  heading:
  accordion_content:
  - heading: Support with your income
    content:
      - subheading:
        links:
        - link_text: Check what benefits and financial support you can get
          href: /check-benefits-financial-support
        - link_text: Find out about the Cost of Living Payment
          href: /guidance/cost-of-living-payment
        - link_text: Check if you’re getting the minimum wage
          href: /am-i-getting-minimum-wage
        - link_text: Apply for Marriage Allowance
          href: /marriage-allowance
        - link_text: Apply for Carer’s Allowance
          href: /carers-allowance
        - link_text: Apply for support with savings if you’re on a low income (Help to Save)
          href: /get-help-savings-low-income
        - link_text: Claim tax relief on work-related expenses
          href: /tax-relief-for-employees
        - link_text: Check how you can deal with your debts
          href: /pay-off-debts
        - link_text: Contact the MoneyHelper service for free, confidential and impartial advice
          href: https://www.moneyhelper.org.uk/
      - subheading: Apply for Universal Credit
        links:
        - link_text: Universal Credit in England, Scotland and Wales
          href: /universal-credit/
        - link_text: Universal Credit in Northern Ireland
          href: https://www.nidirect.gov.uk/campaigns/universal-credit
      - subheading: Apply for Pension Credit if you’re on a low income
        links:
          - link_text: Pension Credit in England, Scotland and Wales
            href: /pension-credit
          - link_text: Pension Credit in Northern Ireland
            href: https://www.nidirect.gov.uk/articles/understanding-pension-credit
      - subheading: Apply for Jobseeker’s Allowance (JSA) if you’re unemployed
        links:
        - link_text: ‘New style’ JSA in England, Scotland and Wales
          href: /jobseekers-allowance
        - link_text: ‘New style’ JSA in Northern Ireland
          href: https://www.nidirect.gov.uk/articles/jobseekers-allowance
  - heading: Support if you’re disabled
    content:
      - subheading:
        links:
        - link_text: Find out about the Cost of Living Payment
          href: /guidance/cost-of-living-payment
      - subheading: Apply for Universal Credit if you’re disabled
        links:
        - link_text: Universal Credit if you’re disabled in England, Scotland or Wales
          href: /health-conditions-disability-universal-credit
        - link_text: Universal Credit in Northern Ireland
          href: https://www.nidirect.gov.uk/campaigns/universal-credit
      - subheading: Apply for Employment and Support Allowance (ESA)
        links:
        - link_text: ‘New style’ ESA in England, Scotland and Wales
          href: /employment-support-allowance
        - link_text: ‘New style’ and ‘Contribution based’ ESA in Northern Ireland
          href: https://www.nidirect.gov.uk/articles/employment-and-support-allowance
      - subheading: Support with living costs if you’re disabled
        links:
        - link_text: Apply for Attendance Allowance if you’re state pension age
          href: /attendance-allowance
        - link_text: Apply for Personal Independence Payment (PIP) in England and Wales
          href: /pip
        - link_text: Apply for Personal Independence Payment (PIP) in Northern Ireland
          href: https://www.nidirect.gov.uk/articles/personal-independence-payment-pip
        - link_text: Apply for Adult Disability Payment in Scotland
          href: https://www.mygov.scot/adult-disability-payment
      - subheading: Support to get or stay in work
        links:
        - link_text: Apply for Access to Work in England
          href: /access-to-work
        - link_text: Apply for Access to Work in Northern Ireland
          href: https://www.nidirect.gov.uk/articles/employment-support-information
      - subheading: Support with travel costs if you’re disabled
        links:
        - link_text: Apply for a disabled person’s railcard from National Rail
          href: https://www.disabledpersons-railcard.co.uk/?52390
        - link_text: Apply for an older or disabled person’s bus pass in Scotland
          href: https://www.transport.gov.scot/concessionary-travel/60plus-or-disabled/
      - subheading: Support if your child is disabled
        links:
        - link_text: Apply for Disability Living Allowance (DLA) for children in England, Wales and Northern Ireland
          href: /disability-living-allowance-children
        - link_text: Apply for Child Disability Payment in Scotland
          href: https://www.mygov.scot/child-disability-payment
  - heading: Support with your bills
    content:
    - subheading:
      links:
      - link_text: Find out how the Energy Price Guarantee limits your energy prices
        href: /government/publications/energy-bills-support/energy-bills-support-factsheet-8-september-2022
      - link_text: Find out about the Cost of Living Payment
        href: /guidance/cost-of-living-payment
      - link_text: Find out about the Energy Bills Support Scheme
        href: /government/news/energy-bills-support-scheme-explainer
      - link_text: Find out about the Winter Fuel Payment and Pensioner Cost of Living Payment
        href: /winter-fuel-payment
      - link_text: Find out about the Warm Home Discount Scheme
        href: /the-warm-home-discount-scheme
      - link_text: Apply for the Cold Weather Payment
        href: /cold-weather-payment
      - link_text: Find out if you can get cheaper phone and broadband on the Ofcom website
        href: https://www.ofcom.org.uk/phones-telecoms-and-internet/advice-for-consumers/costs-and-billing/social-tariffs
      - link_text: Find out how to reduce your water bill and financial support you may be able to get
        href: https://www.ccwater.org.uk/households/help-with-my-bills/
    - subheading: Support with Council Tax
      links:
      - link_text: Apply for a Council Tax reduction in England, Scotland and Wales
        href: /guidance/council-tax-rebate-factsheet
      - link_text: Apply for Rate Relief in Northern Ireland
        href: https://www.nidirect.gov.uk/rates-help
    - subheading: Support with prescriptions and health costs
      links:
      - link_text: Check if you’re eligible for support with prescriptions and health costs
        href: https://services.nhsbsa.nhs.uk/check-for-help-paying-nhs-costs/start
      - link_text: Find out about support with health costs in England and Wales
        href: https://www.nhs.uk/nhs-services/help-with-health-costs
      - link_text: Find out about support with health costs in Scotland
        href: https://www.nhsinform.scot/care-support-and-rights/health-rights/access/help-with-health-costs
      - link_text: Find out about support with health costs in Northern Ireland
        href: https://www.nidirect.gov.uk/articles/help-health-costs
    - subheading: Apply for a Budgeting Loan if you’re claiming benefits
      links:
      - link_text: Budgeting Loans in England, Scotland and Wales
        href: /budgeting-help-benefits
      - link_text: Social Fund Budgeting Loan in Northern Ireland
        href: https://www.nidirect.gov.uk/articles/social-fund-budgeting-loan
  - heading: Support with childcare costs
    content:
    - subheading:
      links:
      - link_text: Check what help you could get with childcare costs
        href: /childcare-calculator
      - link_text: Apply for Child Benefit
        href: /child-benefit
      - link_text: Apply for support with childcare costs for children 11 or under (Tax-Free Childcare)
        href: /tax-free-childcare
      - link_text: Claim back childcare costs if you get Universal Credit
        href: /guidance/universal-credit-childcare-costs
    - subheading: Support with childcare for children aged 2 to 4
      links:
        - link_text: Apply for free childcare for children aged 2 in England
          href: /help-with-childcare-costs/free-childcare-2-year-olds
        - link_text: Apply for 15 hours free childcare for children aged 3 to 4 in England
          href: /help-with-childcare-costs/free-childcare-and-education-for-2-to-4-year-olds
        - link_text: Apply for 30 hours free childcare for children aged 3 to 4 in England
          href: /30-hours-free-childcare
        - link_text: Apply for free childcare for children aged 3 to 4 in Scotland
          href: https://www.mygov.scot/childcare-costs-help/funded-early-learning-and-childcare
        - link_text: Apply for free childcare for children aged 3 to 4 in Wales
          href: https://gov.wales/childcare-3-and-4-year-olds
    - subheading: Support with school costs (for example, equipment and uniforms)
      links:
        - link_text: Apply for support with school uniform costs in Scotland
          href: https://www.mygov.scot/clothing-grants
        - link_text: Apply for support with school costs in Wales
          href: https://gov.wales/pupil-development-grant-access
        - link_text: Apply for support with school uniform costs in Northern Ireland
          href: https://www.eani.org.uk/financial-help/free-school-meals-uniform-grants
    - subheading: Support with school meal costs
      links:
        - link_text: Apply for free school meals in England
          href: /apply-free-school-meals
        - link_text: Apply for free school meals in Scotland
          href: https://www.mygov.scot/school-meals
        - link_text: Apply for free school meals in Wales
          href: https://gov.wales/find-out-about-free-school-meals
        - link_text: Apply for free school meals in Northern Ireland
          href: https://www.nidirect.gov.uk/articles/nutrition-and-school-lunches
    - subheading: Support with school transport costs
      links:
      - link_text: Apply for support with school transport costs in England
        href: /help-home-school-transport
      - link_text: Apply for support with school transport costs in Scotland
        href: https://www.mygov.scot/free-school-transport
      - link_text: Apply for support with school transport costs in Northern Ireland
        href: https://www.eani.org.uk/help-available/home-to-school-transport
    - subheading: Support with childcare costs if your child is disabled
      links:
      - link_text: Apply for Disability Living Allowance (DLA) for children in England, Wales and Northern Ireland
        href: /disability-living-allowance-children
      - link_text: Apply for Child Disability Payment in Scotland
        href: https://www.mygov.scot/child-disability-payment
    - subheading: Support with food and milk for your child
      links:
      - link_text: Apply for Healthy Start vouchers
        href: https://www.healthystart.nhs.uk/how-to-apply/
      - link_text: Apply for Best Start Grant and Best Start Foods in Scotland
        href: https://www.mygov.scot/best-start-grant-best-start-foods
    - subheading: Support with maternity costs
      links:
      - link_text: Apply for the Maternity Grant (Sure Start) in England, Wales and Northern Ireland
        href: /sure-start-maternity-grant
      - link_text: Apply for Best Start Grant and Best Start Foods in Scotland
        href: https://www.mygov.scot/best-start-grant-best-start-foods
  - heading: Support with housing costs
    content:
    - subheading:
      links:
      - link_text: Find out about support with housing costs if you get Universal Credit
        href: /housing-and-universal-credit
      - link_text: Apply for a Discretionary Housing Payment
        href: /government/publications/claiming-discretionary-housing-payments/claiming-discretionary-housing-payments
      - link_text: Apply for support with interest payments on a mortgage or home improvement loan
        href: /support-for-mortgage-interest
      - link_text: Contact your council for help with housing costs and Council Tax
        href: /find-local-council
    - subheading: Check if you’re eligible for Housing Benefit
      links:
      - link_text: Apply for Housing Benefit in England and Wales
        href: /housing-benefit
      - link_text: Apply for Housing Benefit in Scotland
        href: https://www.mygov.scot/claim-housing-benefit
      - link_text: Apply for Housing Benefit in Northern Ireland
        href: https://www.nihe.gov.uk/Housing-Help/Housing-Benefit/Making-a-claim-for-Housing-Benefit
  - heading: Support with travel costs
    content:
    - subheading: Help with rail costs
      links:
      - link_text: Apply for a railcard from National Rail to save money on rail journeys
        href: https://www.railcard.co.uk/
      - link_text: Claim 50% off rail journeys from National Rail if you’re on Universal Credit
        href: https://www.nationalrail.co.uk/times_fares/jobcentre-plus-card.aspx
    - subheading: Help with bus costs
      links:
      - link_text: Apply for an older person’s bus pass in England and Wales
        href: /apply-for-elderly-person-bus-pass
      - link_text: Apply for an older or disabled person’s bus pass in Scotland
        href: https://www.transport.gov.scot/concessionary-travel/60plus-or-disabled/
      - link_text: Apply for an older person’s bus pass in Northern Ireland
        href: https://www.nidirect.gov.uk/articles/60-smartpass-and-senior-65-smartpass
      - link_text: Apply for a disabled person’s bus pass in England
        href: /apply-for-disabled-bus-pass
  - heading: Support for small businesses
    content:
    - subheading:
      links:
      - link_text: Find out how the Energy Bill Relief scheme limits the energy prices of your small business
        href: https://www.gov.uk/guidance/energy-bill-relief-scheme-help-for-businesses-and-other-non-domestic-customers
      - link_text: Find out about support to improve the energy performance of your business
        href: https://www.gov.uk/business-finance-support?keywords=energy
      - link_text: Find out about support with your energy bills on the Citizens Advice website
        href: https://www.citizensadvice.org.uk/consumer/energy/energy-supply/your-small-businesss-energy-supply/your-small-business-cant-afford-its-energy-bills/
