- section_id: business
  section_list:
    - row_title: "Businesses and self-employed"
      list_block: |
        If you trade any goods or services with the EU you'll need to get ready for Brexit.

        For example, you need to take action if you:

        - <a href="/prepare-export-from-uk-after-brexit" data-ecommerce-row="true" data-ecommerce-content-id="e169b2ac-8c90-4789-8e6c-3657729e21b2" data-ecommerce-path="/prepare-export-from-uk-after-brexit">export goods to the EU</a>
        - <a href="/prepare-import-to-uk-after-brexit" data-ecommerce-row="true" data-ecommerce-content-id="db1149f5-f60a-4d02-be0c-9c9db2828665" datecoa-ecommerce-path="/prepare-import-to-uk-after-brexit">import goods from the EU</a>
        - <a href="/transport-goods-from-uk-by-road" data-ecommerce-row="true" data-ecommerce-content-id="9be67e23-bd76-4d60-b6e1-66e0dce5965a" data-ecommerce-path="/transport-goods-from-uk-by-road">transport goods by road</a>
        - <a href="/guidance/exporting-animals-animal-products-fish-and-fishery-products-if-the-uk-leaves-the-eu-with-no-deal" data-ecommerce-row="true" data-ecommerce-content-id="f175dfe5-9f18-4c2f-b673-5c7211902114" data-ecommerce-path="/guidance/exporting-animals-animal-products-fish-and-fishery-products-if-the-uk-leaves-the-eu-with-no-deal">export animals or animal products</a>
        - <a href="/guidance/providing-services-to-any-country-in-the-eu-iceland-liechtenstein-norway-or-switzerland-after-eu-exit" data-ecommerce-row="true" data-ecommerce-content-id="e9dca8c7-04f5-4065-b2ac-70d140512bfa" data-ecommerce-path="/guidance/providing-services-to-any-country-in-the-eu-iceland-liechtenstein-norway-or-switzerland-after-eu-exit">export services to the EU</a>

        [**Find out how to prepare your business for Brexit**](/business-uk-leaving-eu)
- section_id: individuals
  section_list:
    - row_title: "Visiting the EU after Brexit"
      list_block: |
        [**Check what you need to do to visit the EU**](/visit-europe-brexit)

        For example, you'll need to:

        - check your passport
        - get travel insurance to make sure you are covered for healthcare
        - make sure you have the right driving documents
        - get a health certificate for your pet, as UK pet passports will no longer be valid in the EU (contact your vet at least 4 months before you travel)
    - row_title: "UK nationals living in the European Union"
      list_block: |
        [**Check your rights for the country you live in**](/uk-nationals-living-eu)

        Continuing to live and work in an EU country after Brexit depends on the rules in that country.

        For example, you’ll need to:

        - register or apply for residency
        - check if you are covered for healthcare and register if necessary
        - exchange your UK driving licence for a licence issued by the EU country where you live
        - check your passport
    - row_title: "EU citizens living in the United Kingdom"
      list_block: |
        [**Check what you need to do to stay in the UK**](/staying-uk-eu-citizen)

        For example, you should check if you need to apply to the settlement scheme (if you or your family are from the EU, Iceland, Liechtenstein, Norway or Switzerland).
