- section_id: individuals
  section_list:
    - row_title: "Visiting the EU after Brexit"
      list_block: |
        [**Check what you need to do to visit the EU**](/visit-europe-brexit)

        For example, you'll need to:

        - check your passport - you’ll need at least 6 months left on your passport before you travel to the EU (allow 3 weeks to get a new passport)
        - make sure you have the right driving documents
        - get a health certificate for your pet, as UK pet passports will no longer be valid in the EU (contact your vet at least 4 months before you travel)
    - row_title: "UK nationals living in the European Union"
      list_block: |
        [**Check your rights for the country you live in**](/guidance/advice-for-british-nationals-travelling-and-living-in-europe)

        Continuing to live and work in an EU country after Brexit depends on the rules in that country.

        For example, you’ll need to:

        - make sure you have insurance in place to cover healthcare in the EU after Brexit
        - check your access to benefits and pensions
        - exchange your UK driving licence for a licence issued by the EU country where you live
    - row_title: "EU citizens living in the United Kingdom"
      list_block: |
        [**Check what you need to do to stay in the UK**](/staying-uk-eu-citizen)

        For example, you should check if you need to apply for settled status (if you or your family are from the EU, Iceland, Liechtenstein, Norway or Switzerland).
- section_id: business
  section_list:
    - row_title: "Businesses and self-employed"
      list_block: |
        If you trade any goods or services with the EU you'll need to get ready for Brexit.

        For example, you need to take action if you:

        - <a href="/prepare-export-from-uk-after-brexit" data-ecommerce-row="true" data-ecommerce-content-id="e169b2ac-8c90-4789-8e6c-3657729e21b2" data-ecommerce-path="/prepare-export-from-uk-after-brexit">export goods to the EU</a>
        - <a href="/guidance/importing-animals-animal-products-and-high-risk-food-and-feed-not-of-animal-origin-if-the-UK-leaves-the-EU-with-no-deal" data-ecommerce-row='true' data-ecommerce-content-id='4c76a7d6-7f8d-4782-ac89-62e86b147c34' datecoa-ecommerce-path='/guidance/importing-animals-animal-products-and-high-risk-food-and-feed-not-of-animal-origin-if-the-UK-leaves-the-EU-with-no-deal'>import goods from the EU</a>
        - <a href="/transport-goods-from-uk-by-road" data-ecommerce-row="true" data-ecommerce-content-id="9be67e23-bd76-4d60-b6e1-66e0dce5965a" data-ecommerce-path="/transport-goods-from-uk-by-road">transport goods by road</a>
        - <a href="/guidance/exporting-animals-animal-products-fish-and-fishery-products-if-the-uk-leaves-the-eu-with-no-deal" data-ecommerce-row="true" data-ecommerce-content-id="f175dfe5-9f18-4c2f-b673-5c7211902114" data-ecommerce-path="/guidance/exporting-animals-animal-products-fish-and-fishery-products-if-the-uk-leaves-the-eu-with-no-deal">export animals or animal products</a>

        [**Find out how to prepare your business for Brexit**](/business-uk-leaving-eu)
