data:
  read:
    - config/locales/%{locale}/*.yml
  write:
    - ['{:}.*', 'config/locales/%{locale}/\1.yml']
  yaml:
    write:
      line_width: -1
ignore_unused:
  - "organisations.content_item.schema_name.*"
  - "roles.heading.*"
  - "organisations.type.*"
search:
  exclude:
    - app/views/coronavirus_landing_page
