default: &default
  top_level_browse_pages:
    education: education
    childcare-parenting: childcare-parenting
  second_level_browse_pages:
    education:
      find-course: education/further-and-higher-education-skills-and-vocational-training
      school-admissions-transport: education/running-and-managing-a-school
      school-life: education
      student-finance: education/funding-and-finance-for-students
      universities-higher-education: education/further-and-higher-education-skills-and-vocational-training
    childcare-parenting:
      pregnancy-birth: childcare-parenting/pregnancy-and-birth
      fostering-adoption-surrogacy: childcare-parenting/adoption-fostering-and-surrogacy
      financial-help-children: childcare-parenting/financial-help-if-you-have-children
      childcare: childcare-parenting/finding-childcare
      schools-education: education/starting-and-attending-school
      divorce-separation-legal: childcare-parenting/divorce-separation-and-legal-issues
  topics:
    schools-colleges-childrens-services: education
    further-education-skills: education/further-and-higher-education-skills-and-vocational-training
    higher-education: education/further-and-higher-education-skills-and-vocational-training
  subtopics:
    schools-colleges-childrens-services:
      curriculum-qualifications: education/school-curriculum
      data-collection-statistical-returns: education/data-collection-for-pupil-data-and-school-censuses
      exams-testing-assessment: education/school-curriculum
      inspections: education/school-inspections-and-performance
      opening-academy-free-school: education/setting-up-or-changing-the-status-of-a-school
      running-school-college: education/running-and-managing-a-school
      school-behaviour-attendance: education/pupil-wellbeing-behaviour-and-attendance
      school-careers-employment: education/teaching-and-leadership
      school-college-funding-finance: education/school-and-academy-funding-and-provision
      special-educational-needs-disabilities: education/pupils-and-students-with-special-educational-needs-and-disability-send
      adoption-fostering: childcare-parenting/adoption-fostering-and-surrogacy
      early-years: childcare-parenting/childcare-and-early-years
      looked-after-children: childcare-parenting/safeguarding-and-social-care-for-children
      safeguarding-children: childcare-parenting/safeguarding-and-social-care-for-children
      support-for-children-young-people: childcare-parenting/childrens-health-and-welfare
    further-education-skills:
      administration: education/running-a-further-or-higher-education-institution
      apprenticeships: education/apprenticeships-traineeships-and-internships
      learning-records-service: education/learning-records-service-lrs
      vocational-qualifications: education/apprenticeships-traineeships-and-internships
    higher-education:
      administration: education/running-a-further-or-higher-education-institution
      scholarships-for-overseas-students: education/funding-and-finance-for-students#/education/student-grants-bursaries-scholarships





production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
