name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "Jenkinsfile"
      - ".git**"
  pull_request:

jobs:
  test:
    name: Test Rails
    uses: alphagov/govuk-infrastructure/.github/workflows/test-rails.yaml@use-publihing-api-repo-for-content-schemas
    with:
      requiresJavaScript: true
