name: Deploy

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: 'Commit, tag or branch name to deploy'
        required: true
        type: string
        default: 'main'
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
        - integration
        - staging
        - production
        default: 'integration'
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  trigger-deploy-to-integration:
    name: Trigger deploy to integration
    uses: alphagov/govuk-infrastructure/.github/workflows/deploy.yaml@add-deployment-permissions
    with:
      imageTag: "sometag"
      manualDeploy: ${{ github.event_name == 'workflow_dispatch' }}
    secrets:
      WEBHOOK_TOKEN: ${{ secrets.ARGO_EVENTS_WEBHOOK_TOKEN }}
      WEBHOOK_URL: ${{ secrets.ARGO_EVENTS_WEBHOOK_URL }}
      GOVUK_CI_GITHUB_API_TOKEN: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
